### ISSUE TITLE
PA:Review: User Authentication

### ISSUE THREAD

**Issue by valsui** [valsui/TaskLabbit#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
Looks awesome! Just make the following changes, and I will close the issue.
- [x] Going to a random route /#/oweiniouewbrviuwebv should redirect or display a 404 page
- [x] When I try to sign up with all blank fields, the errors push the form so far down that some of the border gets cut off and the login link moves outside of the form.

**Comment by valsui** [comment]
Thanks! I just made the following changes:
1) Redirect to '/' on a random route
2) Fix overflow issue by adding overflow:auto
3) Pushed to heroku

**Comment by eshoule** [comment]
Good job!
