### ISSUE TITLE
PA:Review Choose Tasks

### ISSUE THREAD

**Issue by valsui** [valsui/TaskLabbit#3]
- [x] Users can select from a group of predefined tasks
- [x] Popular tasks appear on the home page
- [x] Other tasks can be searched
- [x] Users cannot choose tasks that do not fit in to a predefined group.
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by valsui** [comment]
Hi Liz! I think that I might be done with this MVP.  To implement this MVP, I passed the task type down through the state. 
1) Clicking a button will route to '/task/new', passing down the task type through the store
2) Searching a task and clicking on the specific task will also route to '/task/new' and pass the task type through the store
   * I implemented a fuzzy finder search and styled to have the drop down render on focus of the input
   * As discussed, since tasks are fixed categories, search was implemented through the front end

**Comment by eshoule** [comment]
Looks great! Good job.
