### ISSUE TITLE
PA:Review Select Price and Confirm

### ISSUE THREAD

**Issue by valsui** [valsui/TaskLabbit#5]
- [x] User will pick time of task
- [x] User will be matched with taskers that perform the task
- [x] User will choose tasker based on hourly price
- [x] User will confirm a tasker
- [x] Adequate styling
- [ ] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by valsui** [comment]
Hey Liz,
Here are some features that I implemented for this MVP:

- Task id gets saved to session storage so that the task can be preserved upon refresh

- Tasker must be logged in to confirm task, otherwise, they will get redirected to the login page, then back to the confirmation page.
      * this implemented a redux cycle to see if a pending task is in the store upon login and will get cleared once the user hits confirm

**Comment by eshoule** [comment]
Good job!
